---
title: "Projet fraudes covid"
author: "LUCEA Lenny"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# BENFORD 6eme VAGUE COVID

```{r}
library(dplyr)
library(tidyr)
library(data.table)
b <-read.csv("covid6.csv",sep=",",header=T)
b <- data.table(b)
distinct(b,b$location)
b <- b[b$date > "2021-12-01",]
drop_na(b)
# on commence à partir de septembre 2021 on s'intéresses aux données récentes.
```

```{r warning=F}
library(tidyr)
library(dplyr)
vec <- function(df){
  x <- c(df$new_cases)
  x <- x[x!=0]
  j=1
  for(i in 1:length(x)){
  if(is.na(x[j])){
    x <- x[-j]
  }
  else{
    j <- j +1
  }
  }
  return(x)
}
benf <- function(dd){
x <- vec(dd)
benlaw <- function(d) log10(1 + 1 / d)
digits <- 1:9
firstDigit <- function(x) substr(gsub('[0.]', '', x), 1, 1)
pctFirstDigit <- function(x) data.frame(table(firstDigit(x)) / length(x))
df <- pctFirstDigit(x)
if(length(x)==0|any(1==df)==F| any(2==df)==F | any(3==df)==F | any(4==df)==F | any(5==df)==F| any(6==df)==F | any(7==df)==F | any(8==df)==F | any(9==df)==F){
    return()
}
else{
baseBarplot <- barplot(df$Freq[1:9], names.arg = digits, xlab = "First Digit",ylab="frequency", ylim = c(0, .35),col="blue",main=dd$location[1])
lines(x = baseBarplot[,1], y = benlaw(digits), col = "red", lwd = 4, 
      type = "b", pch = 23, cex = 1.5, bg = "red")
legend(x="topright", legend=c("Benford distribution","data distribution"),
       col=c("red","blue"), lty=1,lwd=4, cex=0.8)
}
}
```



```{r, warning=F}
name <- distinct(b,b$location)
x <- as.vector(name$`b$location`)
for(i in 1:length(x)){
  bq <- b[b$location==x[i],]
  benf(bq)
} 
```

```{r}
givenames <- function(df){
  name <- distinct(df,df$location)
  w <- 0
  x <- as.vector(name$`df$location`)
  t=0
  for(i in 1:length(x)){
    d <- df[df$location==x[i],]
    v <- vec(d)
    dx <- firstDigit(v)
    if(length(x)==0|any(1==dx)==F| any(2==dx)==F | any(3==dx)==F | any(4==dx)==F | any(5==dx)==F| any(6==dx)==F | any(7==dx)==F | any(8==dx)==F | any(9==dx)==F){
      t=t
    }
    else{
      t=t+1
      w[t]=x[i]
    }
  }
  return(w)
}
```

```{r }
library(BenfordSmoothTest)
T2 <- function(df){
  x <- vec(df)
  benf <- BenfordSmooth.test(x)
  return(benf)
}
```

```{r cache=T,echo = T, results = 'hide'}
w = givenames(b)
pval = 0
test = 0
for(i in 1:length(w)){
  bq <- b[b$location==w[i],]
  T_k <- T2(bq)
  pval[i] <- T_k[3,2]
  test[i] <- T_k[2,2]
}
```
```{r}
mat <- matrix(c(w,test,pval),ncol=3)
mat <- as.data.frame(mat)
colnames(mat)<- c("Pays", "T_2", "p_value")
View(mat)
write.csv(mat,"Benfordvague6.csv")
```

```{r}
#_____________________________ comparaison des tests ______________________________
library(benford.analysis)
library(BenfordTests)
# chi2
ch <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  z <- chisq.benftest(x)
  return(z)
  }
}
# Smirnov
ks <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  y <- ks.benftest(x)
  return(y)
  }
}

# distance euclidienne
edist <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  z <- edist.benftest(x)
  return(z)
  }
}

#Hotelling
joindigit <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  z <- jointdigit.benftest(x)
  return(z)
  }
}

# test de corrélation entre la distribution étudiée et celle de benford
jpsq <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  z <- jpsq.benftest(x)
  return(z)
  }
}

# Chebyshev
mdist <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  z <- mdist.benftest(x)
  return(z)
  }
}
# test d'adéquation basé sur l'écart des moyennes de la distribution
md <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  z <- meandigit.benftest(x)
  return(z)
  }
}

# variante de Freedman du test de Watson
wa <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
  z <- usq.benftest(x)
  return(z)
  }
}
#test de l'arc de mentisse
ma <- function(df){
  x<-vec(df)
  if(length(x)==0){
    return()
  }
  else{
    cp <-benford(x,number.of.digits = 1)
    cf <- marc(cp)
    return(cf)
  }
}
```

```{r}
library(dplyr)
puiss <- function(df){
  name <- distinct(df,df$location)
  x <- as.vector(name$`df$location`)
  a <- rep(0,length(x))
  b <- rep(0,length(x))
  c <- rep(0,length(x))
  d <- rep(0,length(x))
  e <- rep(0,length(x))
  f <- rep(0,length(x))
  g <- rep(0,length(x))
  h <- rep(0,length(x))
  j <- rep(0,length(x))
  for(i in 1:length(x)){
    bq <- df[df$location==x[i],]
    z<-vec(bq)
    if(length(z != 0)){
    ch <- ch(bq)
    ks <- ks(bq)
    edist <- edist(bq)
    jd <- joindigit(bq)
    jpsq <- jpsq(bq)
    mdist <- mdist(bq)
    md <- md(bq)
    wa <- wa(bq)
    ma <- ma(bq)
    if(ch$p.value<=0.05){a[i] <- 1}
    if(ks$p.value <=0.05){b[i] <- 1}
    if(edist$p.value <=0.05){c[i] <- 1}
    if(jd$p.value <=0.05){d[i] <- 1}
    if(jpsq$p.value <=0.05){e[i] <- 1}
    if(mdist$p.value <=0.05){f[i] <- 1}
    if(md$p.value <=0.05){g[i] <- 1}
    if(wa$p.value <=0.05){h[i] <- 1}
    if(ma$p.value <=0.05){j[i] <- 1}
    }
  } 
  w <- c(mean(a),mean(b),mean(c),mean(d),mean(e),mean(f),mean(g),mean(h),mean(j))
  p <- c("chi2","kolmogorov.smirnov","euclidian distance","hoyelling","Joenssen's JP square","Chebyshev","Judge-Schechter","Probability Mass function")
  if(which.max(w)==1){ print("chi2")}
  if(which.max(w)==2){ print("kolmogorov.smirnov")}
  if(which.max(w)==3){ print("euclidian distance")}
  if(which.max(w)==4){print("hoyelling")}
  if(which.max(w)==5){print("Joenssen's JP square")}
  if(which.max(w)==6){print("Chebyshev")}
  if(which.max(w)==7){print("Judge-Schechter")}
  if(which.max(w)==8){print("Probability Mass function")}
  if(which.max(w)==9){print("Mantissa arc Test")}
  print(a)
}
```

```{r}
library("benford.analysis")
name <- distinct(b,b$location)
x <- as.vector(name$`b$location`)
z <- length(as.vector(name$`b$location`))
for(i in 1:z){
  bq <- b[b$location==x[i],]
  w<- vec(bq)
  if(length(w)!=0){plot(benford(w,number.of.digits = 1),main=x[i])}
} 
```

```{r}
library(BenfordSmoothTest)

```

```{r}
b <- b[b$continent=="Europe"]
name <- distinct(b,b$location)
y <- as.vector(name$`b$location`)
for(i in 1:length(y)){
  if(x[i]==1){
    print(y[i])
  }
} 

```
```{r}
for(i in 1:length(y)){
  if(x[i]==0){
    print(y[i])
  }
} 
```
